route:
    repeat_interval: 5m
    group_interval: 5m
    receiver: 'alertmanager-bot'

receivers:
  - name: 'alertmanager-bot'
    webhook_configs:
    - send_resolved: true
      url: 'http://alertmanager-bot:8080'
